### ISSUE TITLE
hyperlink not rendered properly

### ISSUE THREAD

**Issue by jananiravi** [jakekrol/cv-resume#3]
[link](//github.com) format didn't work. Needs to be fixed.
<img width="608" alt="image" src="https://github.com/jakekrol/cv-resume/assets/8397074/7faa4894-40e6-4118-9c1f-377e0929070d">

**Comment by jakekrol** [comment]
Thanks for catching this. I've noticed the markdown link format does not work well with the `vitae` R package I'm using.

I plan on migrating to an overleaf template if I have time before application submissions. For now, I'm going to just include the full links in the `tribble` objects that are passed into vitae functions since the text does not seem to be treated as Markdown.
